server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  sendfile off;
  add_header Cache-Control "no-store";
  location ~ /\.git { deny all; }
  location / { try_files $uri $uri/ =404; }
}
